# version: "3"
# services:
#   react-app:
#     stdin_open: true
#     tty: true
#     build: .
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./src:/app/src
#     # environment:
#     #   - REACT_APP_NAME=LEHEL
#     env_file:
#       - ./.env

version: "3"
services:
  react-app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    # environment:
    #   - REACT_APP_NAME=LEHEL
    env_file:
      - ./.env
