# get the base node image
FROM node
# Workpath inside docker
WORKDIR /app
# copy the dependency list
COPY package.json .
# install node 
RUN npm install
# copy all the files optimization
COPY . . 

ENV REACT_APP_NAME=myName
# Start node developement server 
CMD ["npm","start"]
